name: Bump Version

"on":
  workflow_dispatch:  # Manual trigger

jobs:
  bump:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: '0'

    - name: Bump version and push tag
      id: bump_version
      uses: anothrNick/github-tag-action@a2c70ae
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        PRERELEASE: true

    - name: Update __about__.py file
      run: |
        sed -i "s/__version__ = .*/__version__ = \"${{ steps.bump_version.outputs.new_tag }}\"/" src/gistrun/__about__.py

    - name: Commit and push changes
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions Bot"
        git add src/gistrun/__about__.py
        git commit -m "Bump version to ${{ steps.bump_version.outputs.new_tag }}"
        git push -u origin master
