name: Publish to PyPI

on:
  workflow_dispatch: # Manual trigger

jobs:
  test:
    uses: ./.github/workflows/test.yaml

  bump:
    needs: test
    uses: ./.github/workflows/bump.yml

  publish:
    needs: bump
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.1
        with:
          fetch-depth: '0'

      - name: Set up Python
        uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5.1.0
        with:
          python-version: "3.x"

      - name: Build package
        run: |
          pip install --upgrade pip
          pip install hatch
          hatch build

      - name: Publish package on PyPI
        uses: pypa/gh-action-pypi-publish@81e9d93 # v1.8.14
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
