name: Publish to TestPyPI

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
  release:
    types:
      - prereleased

jobs:
  test-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Build package
        run: |
          pip install --upgrade pip
          pip install hatch
          hatch build

      - name: Publish package on TestPyPI
        uses: pypa/gh-action-pypi-publish@v1.8.14
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository-url: https://test.pypi.org/legacy/
