name: Publish to TestPyPI

"on":
  workflow_run:
    types:
      - completed
  release:
    types:
      - prereleased

jobs:
  test:
    uses: ./.github/workflows/test.yaml

  bump:
    needs: test
    uses: ./.github/workflows/bump.yml

  test-publish:
    needs: bump
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1d96c77 # v4.1.1

      - name: Set up Python
        uses: actions/setup-python@82c7e63 # v5.1.0
        with:
          python-version: "3.x"

      - name: Build package
        run: |
          pip install --upgrade pip
          pip install hatch
          hatch build

      - name: Publish package on TestPyPI
        uses: pypa/gh-action-pypi-publish@81e9d93 # v1.8.14
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository-url: https://test.pypi.org/legacy/
