name: CI

"on": [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@1d96c77 # v4.1.1

      - name: Set up Python
        uses: actions/setup-python@82c7e63 # v5.1.0
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Test with pytest
        run: hatch run test -vv
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
